"""Descripciones curadas de las columnas de cada dataset.

Estas descripciones son el valor agregado del diccionario de datos: traducen
los nombres técnicos (a menudo abreviados de ArcGIS) a su significado de negocio.
Donde el significado no es seguro se marca con "(?)".
"""

# --------------------------------------------------------------------------- #
# DANA — tickets de reclamos operacionales
# --------------------------------------------------------------------------- #
TICKETS = {
    "TICKET": "Identificador único del ticket/orden de trabajo en DANA.",
    "ALCANCE": "Alcance del reclamo: 'general' (afecta a varios) o 'particular' (un predio).",
    "MEDIO RECEPCIÓN": "Canal por el que ingresó el reclamo (presencial, teléfono, correo, web, redes).",
    "FECHA REGISTRO": "Fecha y hora de registro del ticket en oficina.",
    "USUARIO REGISTRA": "Usuario (operador de EPSEL) que registró el ticket. Solo 8 operadores.",
    "DISTRITO": "Distrito declarado del reclamo. 95% Chiclayo.",
    "SUMINISTRO": "Código de suministro del predio (clave para geolocalizar vía catastro comercial). Presente en 73.7%.",
    "DIRECCION": "Dirección textual del reclamo. Presente en 73.7%. No geocodificada.",
    "PERSONA": "Nombre del solicitante. DATO PERSONAL (PII).",
    "DNI": "DNI del solicitante. DATO PERSONAL (PII).",
    "CELULAR": "Celular de contacto. DATO PERSONAL (PII).",
    "TELEFONO FIJO": "Teléfono fijo de contacto. DATO PERSONAL (PII). Presente en ~20%.",
    "CORREO ELECTRÓNICO": "Correo de contacto. En la práctica suele ser el correo del operador, no del ciudadano (ruido).",
    "PARENTESCO": "Relación del solicitante con el titular del suministro (titular, familiar, etc.).",
    "GRUPO": "Grupo organizacional. Constante: 'OPERACIONES' (sin valor analítico).",
    "TIPO GRUPO": "Servicio afectado: AGUA o DESAGUE. Variable de segmentación clave.",
    "CATEGORÍA": "Categoría del ticket. Constante: 'RECLAMO OPERACIONAL' (sin valor analítico).",
    "TIPO DE ATENCION": "Tipología del problema (atoro, fuga, falta de agua, etc.). Variable predictiva principal.",
    "DETALLE DEL TICKET": "Descripción libre del reclamo escrita por el operador. Texto no estructurado.",
    "ESTADO DEL TICKET": "Estado del ticket. Constante: 'Finalizado' (todos cerrados, sin valor analítico).",
    "USUARIO SOLUCIONA": "Usuario que marcó el ticket como solucionado. Solo 8 operadores.",
    "DETALLE DE SOLUCIÓN": "Texto libre del cierre. Mayormente 'ATENDIDA' con muchos errores de tipeo; bajo valor.",
    "FECHA SOLUCION": "Fecha de cierre administrativo (no atención real). Origen: serial de Excel.",
    "DURACION_DIAS": "Derivada: días entre registro y cierre. Es cierre administrativo, no tiempo de atención en campo.",
}

# --------------------------------------------------------------------------- #
# Catastro — esquema ESRI compartido por redes de alcantarillado (primarias/secundarias)
# y, en parte, por buzones. Muchos campos vienen vacíos o como placeholder.
# --------------------------------------------------------------------------- #
REDES = {
    "facilityid": "Identificador del activo (tramo de tubería). Puede repetirse cuando un tramo se parte en varios segmentos.",
    "mainshape": "Forma de la sección. Constante 'Desconocido'.",
    "diameter": "Diámetro nominal de la tubería en mm. Atributo útil.",
    "material": "Material de la tubería (CSN=concreto, PVC, FV=fibra de vidrio, AC=asbesto-cemento, DESC=desconocido).",
    "primarynet": "Flag: pertenece a la red primaria (1) o no (0).",
    "networktyp": "Tipo de red (Emisor, Colector Principal, Red Secundaria, Línea de Impulsión, Desconocido).",
    "matrix": "Campo ESRI sin uso. Vacío.",
    "watertype": "Tipo de agua. Constante 'Desconocido'.",
    "frommh": "Buzón de origen del tramo (topología). VACÍO en origen -> se reconstruye por geometría.",
    "tomh": "Buzón de destino del tramo (topología). VACÍO en origen -> se reconstruye por geometría.",
    "sumflow": "Caudal acumulado. Constante 0.",
    "bedtype": "Tipo de cama de tubería. Constante 'Desconocido'.",
    "exposed": "Tubería expuesta. Constante 'No'.",
    "visitable": "Tubería visitable/registrable (Yes/No).",
    "linedyear": "Año de revestimiento. Vacío.",
    "linertype": "Tipo de revestimiento. Constante 'Desconocido'.",
    "downelev": "Cota de fondo aguas abajo. VACÍO (0) -> se toma de los buzones.",
    "upelev": "Cota de fondo aguas arriba. VACÍO (0) -> se toma de los buzones.",
    "slope": "Pendiente del tramo (por mil/porcentaje). Parcialmente poblada.",
    "reallength": "Longitud real del tramo (m).",
    "enabled": "Flag de habilitado en la red (1/0).",
    "activeflag": "Flag de activo (1/0).",
    "ownedby": "Entidad propietaria (Lam1 = EPSEL Lambayeque).",
    "maintby": "Entidad que mantiene el activo.",
    "lastupdate": "Fecha de última actualización (ESRI). Vacío.",
    "lasteditor": "Último editor (ESRI). Vacío.",
    "lastrevdat": "Fecha de última revisión. Vacío.",
    "condition": "Estado/condición de la tubería. Constante 'Desconocido' (no sirve para riesgo).",
    "obstructio": "Indicador de obstrucción. Constante '0'.",
    "lastrepair": "Fecha de última reparación. Vacío.",
    "repairs": "Nº de reparaciones. Constante 0.",
    "installdat": "Fecha de instalación. Casi vacía y con placeholders (1900/1990) -> inservible para antigüedad.",
    "installer": "Instalador. Constante 'Desconocido'.",
    "estimatedr": "Fecha estimada de reemplazo. Vacío.",
    "expedientc": "Código de expediente. Vacío.",
    "sapcode": "Código SAP del activo. Vacío.",
    "district": "Código de distrito (INEI, p.ej. 140101 = Chiclayo).",
    "centercost": "Centro de costo. Vacío.",
    "terraintyp": "Tipo de terreno. Constante 'Desconocido'.",
    "changereas": "Motivo de cambio. Constante 'Carta'.",
    "changedocu": "Documento de cambio. Vacío.",
    "installati": "Campo de instalación (numérico). Constante 0.",
    "montante": "Montante. Constante 0.",
    "nomptar": "Nombre de PTAR asociada. Constante 'Desconocido'.",
    "ptofinalde": "Punto final de descarga. Constante 'Desconocido'.",
    "networkloc": "Ubicación de la red (Vía Pública). Valores con grafías inconsistentes.",
    "SHAPE__Len": "Longitud de la geometría calculada por ArcGIS (en unidades del CRS).",
    "created_us": "Usuario que creó el registro en el GIS.",
    "created_da": "Fecha de creación del registro en el GIS (oct-nov 2025; es digitalización, no instalación).",
    "last_edite": "Último usuario que editó el registro en el GIS.",
    "last_edi_1": "Fecha de última edición del registro en el GIS.",
}

# --------------------------------------------------------------------------- #
# Catastro — buzones (nodos de alcantarillado)
# --------------------------------------------------------------------------- #
BUZONES = {
    "facilityid": "Identificador del buzón. Con duplicados (20.147 únicos de 21.354).",
    "mhtype": "Tipo de buzón (Estándar, Arranque, Otro, Desconocido).",
    "mhshape": "Forma del buzón (Tubular, Desconocido).",
    "diameter": "Diámetro del buzón. Constante 0.",
    "watertype": "Tipo de agua (Aguas residuales / Desconocido).",
    "cvtype": "Tipo de tapa/cámara (Concrete / Desconocido).",
    "wallmat": "Material de la pared (CR=concreto, DESC).",
    "flowdir": "Dirección de flujo dominante (Oeste, Sur, etc.). Presente 94%. Clave para topología.",
    "sumflow": "Caudal acumulado. Constante 0.",
    "accesstype": "Tipo de acceso. Constante 'Desconocido'.",
    "specialfal": "Falla especial. Constante 'No'.",
    "placement": "Ubicación del buzón (Berma / Desconocido).",
    "invert": "Cota de fondo del buzón (m). COMPLETA (100%). Clave para reconstruir pendientes/topología.",
    "rimelev": "Cota de tapa del buzón (m). COMPLETA (100%).",
    "cutdepth": "Profundidad de excavación = rimelev - invert (m).",
    "locdesc": "Descripción de ubicación. Mayormente vacía.",
    "gpsdate": "Fecha de toma GPS. Vacío (no se registró en campo).",
    "rotation": "Rotación del símbolo. Constante 0.",
    "enabled": "Flag de habilitado (1/0).",
    "activeflag": "Flag de activo (1/0).",
    "ownedby": "Entidad propietaria.",
    "maintby": "Entidad que mantiene.",
    "lastupdate": "Última actualización (ESRI). Vacío.",
    "lasteditor": "Último editor. Vacío.",
    "lastrevdat": "Última revisión. Vacío.",
    "condition": "Condición del buzón. Constante 'Desconocido'.",
    "lastrepair": "Última reparación. Vacío.",
    "repairs": "Nº de reparaciones. Constante 0.",
    "installdat": "Fecha de instalación. Casi vacía, placeholder 1900. Inservible.",
    "installer": "Instalador. Constante 'Desconocido'.",
    "expedientc": "Expediente. Vacío.",
    "sapcode": "Código SAP. Vacío.",
    "district": "Código de distrito (INEI).",
    "centercost": "Centro de costo. Vacío.",
    "ancillaryr": "Rol auxiliar (ESRI). Constante 0.",
    "x": "Coordenada X en UTM 17S (EPSG:32717) embebida en la tabla. ¡Coordenadas reales disponibles!",
    "y": "Coordenada Y en UTM 17S (EPSG:32717) embebida en la tabla.",
    "z": "Coordenada Z. Constante 0.",
    "bzprim": "Flag buzón primario. Constante 0.",
    "num_salida": "Nº de salidas. Constante 0.",
    "ubicado": "Indicador de buzón ubicado en campo (Yes/NO).",
    "vinculacio": "Vinculación a tramo de tubería (p.ej. 'CP: FID_047235'). Útil para enganchar nodo-arista.",
    "created_us": "Usuario que creó el registro en el GIS.",
    "created_da": "Fecha de creación del registro en el GIS.",
    "last_edite": "Último usuario que editó el registro en el GIS.",
    "last_edi_1": "Fecha de última edición del registro en el GIS.",
}

# --------------------------------------------------------------------------- #
# Catastro — manzanas (polígonos de manzana, Sector 09)
# --------------------------------------------------------------------------- #
MANZANAS = {
    "sector": "Sector catastral. Constante '09' (solo se entregó este sector).",
    "provincia": "Código de provincia. Constante '01' (Chiclayo).",
    "localidad": "Código de localidad. Constante '01'.",
    "manzana": "Código jerárquico de manzana (provincia.distrito.sector.manzana).",
    "codante": "Código catastral anterior de la manzana.",
    "SHAPE__Len": "Perímetro de la manzana (unidades del CRS, Web Mercator -> inflado ~1.4%).",
    "SHAPE__Are": "Área de la manzana (unidades del CRS; recalcular en UTM para m² reales).",
    "created_us": "Usuario que creó el registro en el GIS.",
    "created_da": "Fecha de creación del registro en el GIS.",
    "last_edite": "Último usuario que editó el registro en el GIS.",
    "last_edi_1": "Fecha de última edición del registro en el GIS.",
}

# --------------------------------------------------------------------------- #
# Catastro — RED_AGUA (solo .dbf, sin geometría; export de ArcGIS Utility Network)
# --------------------------------------------------------------------------- #
RED_AGUA = {
    "id": "Identificador secuencial de fila.",
    "ASSETGROUP": "Grupo de activo (Utility Network). Código numérico.",
    "ASSETTYPE": "Tipo de activo dentro del grupo. Código numérico.",
    "ASSOCIATIO": "Estado de asociación (Utility Network). Constante 0.",
    "ISCONNECTE": "Estado de conexión en la red. Constante 2.",
    "FROMDEVICE": "Terminal de dispositivo origen. Constante 0.",
    "TODEVICETE": "Terminal de dispositivo destino. Constante 0.",
    "CREATIONDA": "Fecha de creación del registro (2021). Pista de la antigüedad de la digitalización.",
    "CREATOR": "Usuario creador (estación de trabajo).",
    "LASTUPDATE": "Fecha de última actualización del registro.",
    "UPDATEDBY": "Usuario de última actualización.",
    "SHAPE_Leng": "Longitud de la geometría (la geometría .shp NO está disponible).",
    "GLOBALID": "GUID global del activo (ESRI).",
    "cpsubnetwo": "Subred (Utility Network). Constante 'Unknown'.",
    "SUPPORTEDS": "Subred soportada. Constante 'Unknown'.",
    "SystemSubn": "Subred de sistema. Constante 'Unknown'.",
    "PressureSu": "Subred de presión. Constante 'Unknown'.",
    "IsolationS": "Subred de aislamiento. Constante 'Unknown'.",
    "DMASubnetw": "Subred DMA (distrito de medición). Constante 'Unknown'.",
    "installdat": "Fecha de instalación. Vacío.",
    "assetid": "ID de activo (con duplicados).",
    "ownedby": "Propietario (código). Constante 1.",
    "maintby": "Mantenedor (código). Constante 1.",
    "notes": "Notas libres. Casi vacío.",
    "diameter": "Diámetro de la tubería de agua (en pulgadas: 4, 6, 10, 12...).",
    "measuredle": "Longitud medida del tramo (m).",
    "adddetails": "Detalles adicionales (flag). Constante 0.",
    "lifecycles": "Estado de ciclo de vida (código).",
    "bondedinsu": "Aislamiento (Utility Network). Constante 0.",
    "cptraceabi": "Trazabilidad (Utility Network). Código.",
    "inserviced": "Fecha de puesta en servicio. Vacío.",
    "retireddat": "Fecha de retiro. Vacío.",
    "material": "Material de la tubería de agua (código numérico ESRI).",
    "cpoverride": "Override de subred. Constante 0.",
    "designtype": "Tipo de diseño (código).",
    "spatialsou": "Fuente espacial del dato (código de precisión).",
    "spatialcon": "Confianza espacial (código).",
    "networktyp": "Tipo de red de agua (código numérico).",
    "RENOVACION": "Texto de renovación. Casi vacío.",
}

# Mapa nombre_dataset -> dict de descripciones
BY_DATASET = {
    "tickets": TICKETS,
    "manzanas": MANZANAS,
    "buzones": BUZONES,
    "redes_primarias": REDES,
    "redes_secundarias": REDES,
    "red_agua": RED_AGUA,
}
